### ISSUE TITLE
FreeIPA version compatibility.

### ISSUE THREAD

**Issue by soulhunter** [freeipa/ansible-freeipa#13]
Hi!

I know this is more a discussion/question than an issue, as I understand this is work in progress and that no official release is still available.

I was (still am, tbh) incredibly excited when I first found this project, and even more when, from the content of roles/ipaserver/vars/ it would seem like it supported RHEL 7.  Well, it turns out it seems to require FreeIPA 4.6, which is not available even on RHEL 7.4.  I tried to force the bar a bit and changed 40600 to 40500 in module_utils/ansible_ipa_server.py, and when I tried to run again it complains:

`fatal: [ipa1.test.local]: FAILED! => {"changed": false, "module_stderr": "Shared connection to ipa1.test.local closed.\r\n", "module_stdout": "ipa: INFO: Checking DNS domain test.local., please wait ...\r\nipa: INFO: Checking DNS domain 7.20.10.in-addr.arpa., please wait ...\r\nipa: WARNING: Invalid IP address fe80::7143:416:27fa:18f8 for ipa1.test.local: cannot use link-local IP address fe80::7143:416:27fa:18f8\r\nTraceback (most recent call last):\r\n  File \"/tmp/ansible_pXzngc/ansible_module_ipaserver_prepare.py\", line 263, in <module>\r\n    main()\r\n  File \"/tmp/ansible_pXzngc/ansible_module_ipaserver_prepare.py\", line 223, in main\r\n    dns.install_check(False, api, False, options, options.host_name)\r\n  File \"/usr/lib/python2.7/site-packages/ipaserver/install/dns.py\", line 312, in install_check\r\n    reverse_zones_unattended_check, search_reverse_zones\r\n  File \"/usr/lib/python2.7/site-packages/ipaserver/install/bindinstance.py\", line 458, in check_reverse_zones\r\n    if not options.allow_zone_overlap:\r\nAttributeError: 'options_obj' object has no attribute 'allow_zone_overlap'\r\n", "msg": "MODULE FAILURE", "rc": 0}`

Which at least is now a different error...

Before spending too much time on this, could you confirm if there are plans to make this compatible with older releases (like 4.5 found on RHEL 7)?  if so, I might go ahead and troubleshoot this and maybe help a bit.

Thanks in advance!

Ildefonso

**Comment by t-woerner** [comment]
Yes, there are plans to make the server role compatible to version 4.5.

**Comment by t-woerner** [comment]
The use of the ipaserver role with RHEL-7.4 is now possible. Also the use of reverse zones is now possible without running into an error. Please make sure that you have the latest three commits applied to your ansible-freeipa tree:
3edc1bedca49c4ac865b0250add66a512279a536 - Make ipaserver role working with ipa 4.5(.4)
d8c3d34369ea77e68339129773edae06d5a7d973 - ipaserver/library/ipaserver_test.py: Use check_zone_overlap directly
a0040ee8211a7bd6d648ed9a7c2ff2e3153be777 - ipaserver/library/ipaserver_prepare.py: Add missing allow_zone_overlap
