### ISSUE TITLE
error installing freeipa-ansible_freeipa-0.3.6.tar.gz

### ISSUE THREAD

**Issue by jshen1976** [freeipa/ansible-freeipa#571]
My environment doesn't have internet access, I downloaded freeipa-ansible_freeipa-0.3.6.tar.gz, then tried following install
ansible-galaxy collection install -p /usr/share/ansible/collections freeipa-ansible_freeipa-0.3.6.tar.gz 

Got error:
ERROR! Unexpected Exception, this is probably a bug: invalid semantic version 'A.B.C'

**Comment by rjeffman** [comment]
If you use the tarball, you don't need to install it from Ansible Galaxy.

Unpack the `tar.gz` file to a directory, and follow the guidelines under section `GIT repo` from the [README](README.md).

**Comment by jnm27** [comment]
We want to use galaxy as part of version control. All other packages work - why not this one?

**Comment by jshen1976** [comment]
unpack the tar file freeipa-ansible_freeipa-0.3.6.tar.gz works, but I would like to install it via ansible-galaxy for version control like jnm27 pointed out.

**Comment by rjeffman** [comment]
Can provide the output of `ansible-galaxy --version`?

I just tested with ansible-galaxy 2.9.21 and it worked:

```
[rjeffman@dantooine test]$ ansible-galaxy collection install freeipa-ansible_freeipa-0.3.6.tar.gz 
Process install dependency map
Starting collection install process
Installing 'freeipa.ansible_freeipa:0.3.6' to '/home/rjeffman/.ansible/collections/ansible_collections/freeipa/ansible_freeipa'
```

**Comment by jnm27** [comment]
TFDM==>ansible-galaxy --version
ansible-galaxy [core 2.11.0]
  config file = /home/users/gbg/e348506/git/clone/ile/playbooks/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible-galaxy
  python version = 3.8.3 (default, Aug 18 2020, 08:56:04) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
  jinja version = 3.0.0
  libyaml = True
root@vnat.vlab26.tfdm.nas.faa.g

**Comment by jshen1976** [comment]
ansible environment also has no internet connection

**Comment by rjeffman** [comment]
Installation worked with Ansible up to version 2.10.10.

It did not work with 2.11.0, but I got a different error:
```
ERROR! Unexpected Exception, this is probably a bug: 'NoneType' object has no attribute 'items'
```

This might be either an issue with Ansible 2.11 (Ansible 4), or some issue we will have to fix later.

As of now, the usage of ansible-freeipa with Ansible 2.11 is broken, so I suggest using any version between 2.8 and 2.10, including those.

**Comment by jshen1976** [comment]
I tried to modify the tar file util/build-galaxy-release.sh to hard code in the version number, that workaround the invalid semantic version 'A.B.C' error
util/build-galaxy-release.sh
#galaxy_version=$(git describe --tags | sed -e "s/^v//")
galaxy_version="0.3.6"

Then I tried it again, I got the 'NoneType' object has no attribute 'items' error next.

to get pass the version error by hard code in the version, then I hit the 'NoneType' error next

**Comment by t-woerner** [comment]
Why aren't you using the galaxy release from `https://galaxy.ansible.com/freeipa/ansible_freeipa`? There is a download link: `https://galaxy.ansible.com/download/freeipa-ansible_freeipa-0.3.6.tar.gz`

This is working for me without issues with Ansible 2.9.21: `ansible-galaxy collection install freeipa-ansible_freeipa-0.3.6.tar.gz`
With 2.11.1 I am also running into the `ERROR! Unexpected Exception, this is probably a bug: 'NoneType' object has no attribute 'items'` error.
